name: Code Coverage Report
on:
  push:
    branches:
      - master
jobs:
  code-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
      - name: Download Command Line Tools
        run: |
            mkdir -p $HOME/android-sdk/cmdline-tools
            curl -fo sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
            mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

      - name: Install Android SDK Packages
        run: |
                echo "sdk.dir=$HOME/android-sdk" > local.properties
                yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
                $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator" "system-images;android-30;default;x86_64"

      - name: Set up environment variables
        run: |
                echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
                echo "export PATH=$PATH:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
                echo "export PATH=$PATH:$HOME/android-sdk/emulator" >> $GITHUB_ENV
      - name: Start emulator
        run: ./start-emulator.sh
      - name: Run Code Coverage Report
        run: ./gradlew media-capture:runDebugCoverageReport
