name: Unit Tests
on:
  push:
    branches:
      - master
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Tests
        run: ./gradlew media-capture:testDebugUnitTest

